---
title: "contas"
author: "Bia"
date: "24 de maio de 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Latex

MQ $\rightarrow$ mínimos quadrados
<p>
$y_{i}= \alpha + \beta x_{i} + \varepsilon_{i} \rightarrow \varepsilon_{i} = y_{i} - \alpha - \beta x_{i}$
<p>
Como $x$ tem valores 0 ou 1:
<p>
$x = 0 \rightarrow \varepsilon_{i} = y_{i}- \alpha$<p>
$x= 1 \rightarrow \varepsilon_{i} = y_{i} - \alpha - \beta$
<p>
$\varepsilon_{i} = y_{i} - \alpha - \beta x_{i} \rightarrow \sum_{i=i}^n ( \varepsilon_{i})^2 = \sum_{i=1}^n ( y_{i} - \alpha - \beta x_{i} )^2 = \sum_{i=1}^n (y_{i}^2 + \alpha^2 + \beta^2 x_{i}^2 - 2 \alpha y_{i} - 2 \beta x_{i} y_{i} + 2 \alpha \beta x_{i})$
<p>

Fazendo os mínimos quadrados:<p>
$\frac{d}{d\alpha} \sum_{i=1}^n ( y_{i}^2 + \alpha^2 + \beta^2 x_{i}^2 - 2 \alpha y_{i} - 2 \beta x_{i} y_{i} + 2 \alpha \beta x_{i})$
$= \sum_{i=1}^n 2 \alpha - 2 y_{i} + 2 \beta x_{i} = 2 [n \alpha - \sum_{i=1}^n y_{i} + \beta \sum_{i=1}^n x_{i}]$
<p>
Para provar que é o mínimo:
<p>
$\frac{d}{d \alpha} \sum_{i=1}^n 2 \alpha - 2 y_{i} + 2 \beta x_{i} = 2 > 0$
<p>
------<p>
$\frac{d}{d \beta} \sum_{i=1}^n ( y_{i}^2 + \alpha^2 + \beta^2 x_{i}^2 - 2 \alpha y_{i} - 2 \beta x_{i} y_{i} + 2 \alpha \beta x_{i}) = \sum_{i=1}^n 2 \beta x_{i}^2 - 2 x_{i} y_{i} +2 \alpha x_{i}$
<p>
$= 2 [\beta \sum_{i=1}^n x_{i}^2 - \sum_{i=1}^n x_{i} y_ {i} + \alpha \sum_{i=1}^n x_{i}]$
<p>
Para provar que é o mínimo:
<p>
$\frac{d}{d \beta} \sum_{i=1}^n 2 \beta x_{i}^2 - 2 x_{i} y_{i} +2 \alpha= 2 \sum_{i=1}^n x_{i}^2 >0$ 
(é sempre positiva dado que $x_{i}$ está ao quadrado)<p>
------<p>
Se:<p>

$n \alpha - \sum_{i=1}^n y_{i} + \beta \sum_{i=1}^n x_{i} = 0$<P>
$\beta \sum_{i=1}^n x_{i}^2 - \sum_{i=1}^n x_{i} y_{i} + \alpha \sum_{i=1}^n = 0$<p>
então<p>
$\alpha = \frac{1}{n} \sum_{i=1}^n y_{i} - \frac{ \beta}{n} \sum_{i=1}^n x_{i}$<p>
$\beta = \frac{ \sum_{i=1}^n x_{i} y_{i} - \alpha \sum_{i=1}^n x_{i}}{\sum_{i=1}^n x_{i}^2}$<p>
Substituindo $\alpha$ em $\beta$ temos:<p>
$\beta = \frac{ \sum_{i=1}^n x_{i} y_{i} - \frac{1}{n} \sum_{i=1}^n y_{i} \sum_{i=1}^n x_{i} + \frac{\beta}{n} \sum_{i=1}{n}x_{i} \sum_{i=1}^n} {\sum_{i=1}^n x_{i}^2}$<p>
$\rightarrow \beta = \frac{\sum_{i=1}^n x_{i} Y_{i} - \frac{1}{n} \sum_{i=1}^n y_{i} \sum_{i=1}^n x_{i}}{\sum_{i=1}^n x_{i}^2 - \frac{1}{n} \sum_{i=1}^n x_{i} \sum_{i=1}^n x_{i}}$<p>
------<p>
$\sum_{i=1}^n y_{i}= \sum_{j=1}^n y_{1j} + \sum_{j=1}^n y_{2j}$<p>
sendo $y_{1}$ os valores de $y$ quando $x=0$ e $y_{2}$ os valores de $y$ correspondentes a $x=1$<p>
Sabemos que $\sum_{i=1}^n x_{i} y_{i} = \sum_{j=1}^ny_{2j}$ e que $\sum_{i=1}^n x_{i} = n_{2} = \sum_{i=1}^n x_{i}^2$<p>
$\beta = \frac{\sum_{i=1}^n y_{2j} -  \frac{1}{n} \sum_{i=1}^n y_{i}(n_{2})}{n_{2}- \frac{(n_{2})^2}{n}}$<p>
$\beta = \frac{n \sum_{i=1}{n}y_{2j} - \sum_{i=1}^n y_{i}(n_{2})(\frac{1}{n_{2}})}{n(n_{2})-(n_{2})^2}$<p>
$\beta = \frac{n \bar y_{2} - \sum_{i=1}^n y_{i}}{n-n_{2}}$<p>
$\beta = \frac{n \bar y_{2} - \sum_{i=1}^n y_{i}}{n_{1}}$<p>
$\beta = \frac{n \bar y_{2}}{n_{1}} - \frac{ \sum_{i=1}^n y_{1j}}{n_{1}} - \frac{\sum_{i=1}^n y_{2j}}{n_{1}}$<p>
$\beta = \frac{n}{n_{1}}\bar y_{2} - \bar y_{1} - \frac{n_{2} \bar y_{2}}{n_{1}}$<p>
$\beta = \frac{(n_{1}+n_{2})\bar y_{2} - n_{1}\bar y_{1} - n_{2} \bar y_{2}}{n_{1}}$<p>
$\rightarrow \beta = \bar y_{2} - \bar y_{1}$<p>
------<p>
Substituindo $\beta = \bar y_{2} - \bar y_{1}$ em $\alpha$<p>
$\alpha= \frac{1}{n} \sum_{i=1}^n y_{1} - \frac{ \bar y_{2} - \bar y_{1}}{n} \sum_{i=1}^n x_{i}$<p>
$\alpha= \frac {\sum_{i=1}^n y_{1} - n_{2} \bar y_{2} + n_{2} \bar y_{1}}{n}$<p>
$\alpha=\frac {\sum_{j=1}^n y_{1j} + \sum_{j=1}^n y_{2j} - n_{2} \bar y_{2} + n_{2} \bar y_{1}}{n}$<p>
$\alpha=\frac {n_{1} \frac{\sum_{j=1}^n y_{1j}}{n_{1}} + n_{2} \frac{\sum_{j=1}^n y_{2j}}{n_{2}} - n_{2} \bar y_{2} + n_{2} \bar y_{1}}{n}$<p>
$\alpha= \frac{n_{1} \bar y_{1} + (n_{2} \bar y_{2} - n_{2} \bar y_{2}) + n_{2} \bar y_{1}}{n}$<p>
$\alpha= \frac{(n_{1}+n_{2}) \bar y_{1}}{n}$<p>
$\rightarrow \alpha = \bar y_{1}$